FROM openjdk:8
RUN apt-get update && apt-get -y install maven && apt-get -y install unzip
ADD . /usr/local/act
RUN cd /usr/local/act/ && chmod 755 run_dev && chmod 755 run_prod && chmod 755 build_dev && chmod 755 build_prod && chmod 755 service.sh && chmod 755 service-runner.sh 
RUN /usr/local/act/build_STATE
CMD [""]
ENTRYPOINT ["/usr/local/act/run_STATE"]
